Finish _.include() (note)
Pretty handy function. Can't figure out why I'm hitting the 'TypeError: predicateFind is not a function' in the NaN portions.  I see that it is a conditional on createIndexFinder() but I'm not sure what's causing the issue. Will be cool to discover that later.